# Generated by Django 4.1 on 2022-10-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.CharField(max_length=50, verbose_name='ballast')),
                ('write', models.TextField(verbose_name='about me')),
            ],
        ),
    ]
